version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.0.442
    environment:
      JVM_OPTS: -Xmx512M
    steps:
      - checkout
      - restore_cache:
          key: shadow-cljs-hooks-{{ checksum "deps.edn" }}
      - run: make test
      - save_cache:
          paths:
            - ~/.m2
          key: shadow-cljs-hooks-{{ checksum "deps.edn" }}
